export default {
  firstDay: 0,
  showLimit: 3,
  locale: 'ja',
  fullDayNames: false,
  fullMonthNames: false,
  class: 'vue-calendar',
  componentName: 'vue-calendar',
  yearSuffix: '年',
  translations: {
    showMore: 'もっと見せる',
    dayNameShort: ['日', '月', '火', '水', '木', '金', '土'],
    dayNameLong: [
      '日曜日',
      '月曜日',
      '火曜日',
      '水曜日',
      '木曜日',
      '金曜日',
      '土曜日',
    ],
    monthNameShort: [
      '1月',
      '2月',
      '3月',
      '4月',
      '5月',
      '6月',
      '7月',
      '8月',
      '9月',
      '10月',
      '11月',
      '12月',
    ],
    monthNameLong: [
      '1月',
      '2月',
      '3月',
      '4月',
      '5月',
      '6月',
      '7月',
      '8月',
      '9月',
      '10月',
      '11月',
      '12月',
    ],
  },
}
